name: "test action"
author: "Zheng Bote"
description: "test."

inputs:
  name:
    description: "your name"
    required: true
    default: "ego"

outputs:
  message:
    description: "the output"

runs:
  using: "composite"
  steps:
    - name: "run bash"
      shell: bash
      run: |
        echo '::info::starting shellscript'
        ./test.sh ${{ inputs.name }}
