name: "test action"
author: "Zheng Bote"
description: "test."

inputs:
  name:
    description: "your name"
    required: true
    default: "ego"

outputs:
  message:
    description: "the output"

run: |
  ./test.sh
shell: bash
