name: "test action"
author: "Zheng Bote"
description: "test."

inputs:
  name:
    description: "your name"
    required: true
    default: "ego"

outputs:
  message:
    description: "the output"

runs:
  name: run bash
  shell: bash
  run: |
    ./test.sh
