name: "test action"
author: "Zheng Bote"
description: "test."

branding:
  icon: "point"
  color: "red"

inputs:
  name:
    description: "your name"
    required: true
    default: "ego"

outputs:
  message:
    description: "the output"
    value: ${{ steps.run-bash.outputs.message}}

runs:
  using: "composite"
  steps:
    - name: "run bash"
      id: run-bash
      shell: bash
      run: |
        ./test.sh ${{ inputs.name }}
      timeout-minutes: 5
