name: "test action"
author: "Zheng Bote"
description: "test."

branding:
  icon: "point"
  color: "red"

inputs:
  name:
    description: "your name"
    required: false
    default: "ego"

outputs:
  message:
    description: "the output"
    value: ${{ steps.run-bash.outputs.message}}

runs:
  using: "composite"
  steps:
    - name: "run bash"
      id: run-bash
      shell: bash
      run: |
        echo '::info::starting shellscript'
        gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/Zheng-Bote/gh-a_page_list-tags/docs/readme.md
